### ISSUE TITLE
0.0.11 does not contain a dist folder in its release

### ISSUE THREAD

**Issue by Technohacker** [domoritz/clingo-wasm#224]
Hello,
While working with this package in Angular and Node, I faced issues with it failing to import correctly on both. Traced it back to the 0.0.11 release not containing the final build files in the `dist/` folder. Reverting to 0.0.10 fixed it. Just wanted to give a heads up on the breakage :)

**Comment by Technohacker** [comment]
Further, I believe the package also assumes a hard-coded path for the WASM file at `/dist/clingo.wasm`, which breaks it on Angular's Webpack build. Maybe this could be made configurable?

**Comment by domoritz** [comment]
Thanks for the issue report. Can you send a pull request to fix the build script?

**Comment by peter-gy** [comment]
Hi @domoritz, I just opened PR #226 to fix this.

**Comment by domoritz** [comment]
Thank you. Fixed in 0.0.12
