### ISSUE TITLE
`ClingoResult` type definition

### ISSUE THREAD

**Issue by peter-gy** [domoritz/clingo-wasm#229]
Is there a reason why `ClingoResult.Call.Witnesses` has no `Costs: number[]` member?

Currently, the interface is defined as:

```typescript
export interface ClingoResult {
    Solver?: string;
    Calls: number;
    Call: {
        Witnesses: {
            Value: string[];
        }[];
    }[];
    Models: {
        More: "yes" | "no";
        Number: number;
        Brave?: "yes" | "no";
        Consequences?: any;
    };
    Result: "SATISFIABLE" | "UNSATISFIABLE";
    Time: {
        CPU: number;
        Model: number;
        Solve: number;
        Total: number;
        Unsat: number;
    };
    Warnings: string[];
}
```

It would be nice to be able to access `Costs` without the need to cast the result object to `any`, as it is a valuable piece of data when it comes to ranking recommendations.

Furthermore, the `Result` field can also have more values, as per [the test suite of clingo](https://github.com/potassco/clingo/blob/52c7a2e84c37603a5d6ecd20abfea39b61b1316f/app/clingo/tests/run.py#L85):

- `"SATISFIABLE"`
- `"UNSATISFIABLE"`
- `"UNKNOWN"`
- `"OPTIMUM FOUND"`

My suggestion would be:

```typescript
export interface ClingoResult {
    Solver?: string;
    Calls: number;
    Call: {
        Witnesses: {
            Value: string[];
            Costs: number[];
        }[];
    }[];
    Models: {
        More: "yes" | "no";
        Number: number;
        Brave?: "yes" | "no";
        Consequences?: any;
    };
    Result: "SATISFIABLE" | "UNSATISFIABLE" | "UNKNOWN" | "OPTIMUM FOUND";
    Time: {
        CPU: number;
        Model: number;
        Solve: number;
        Total: number;
        Unsat: number;
    };
    Warnings: string[];
}
```

If you agree, I would open a PR for this.

**Comment by domoritz** [comment]
Good catches. The result type is very incomplete and I just added some more properties. It's probably still not completely correct.
