### ISSUE TITLE
Create a proper JS API

### ISSUE THREAD

**Issue by domoritz** [domoritz/clingo-wasm#4]
Something like

```ts
import clingo from 'clingo';

const result = clingo('a. b :- a.');

console.log(result);
```

**Comment by rkaminsk** [comment]
Here is a late reply. I think that you can additionally export the functions from the clingo API and then use them from JavaScript. Just list them in `app/web/CMakeLists.txt`.

**Comment by domoritz** [comment]
We now have a simple JS API. It's not even close to the full Clingo API but allows running programs and getting results.
