### ISSUE TITLE
Running just gringo

### ISSUE THREAD

**Issue by haz** [domoritz/clingo-wasm#62]
This may already be possible, so perhaps not worthy of an issue, but is there any chance we could get access to just gringo instead of the full clingo run? Thanks!

**Comment by domoritz** [comment]
I think you can pass `--text` as an argument to run only gringo. However, right now I expect the output to be JSON. The code would need to be changed. Do you want to take a stab at it?

**Comment by haz** [comment]
This seems to do precisely what we need, thanks! We can lift the output from the `output` variable, just like vanilla clingo, and that's all we need for our application.

Will close this out.
